### ISSUE TITLE
The option "Move featured entries to top" breaks calculation on page 2

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/Featured-Entries#16]
1) Assuming you have 15 entries in total.
2) 7 entries of those are featured.
3) Your View pagination is set to 12 items per page. Pagination is showing 3 pages.
4) On your first page, 12 entries show up (7 featured plus 5 non-featured)
5) On your second page, 10 entries show up (7 features, plus the remaining 3 non-featured).

At this point, the pagination widget doesn't show up anymore.

GV: 2.0.10 and Featured E: 2.0.1

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/991397300387786/991502874095054)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/596151057/15317?folderId=408730

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/613190264/15721?folderId=408730

**Comment by soulseekah** [comment]
Please test https://github.com/gravityview/Featured-Entries/commit/a7995e90e682ddd062627b080abb91b5841c81b3 should have solved this. Thank you!
