### ISSUE TITLE
Missing entries when "Move featured entries to top" used in 2 Views on same page

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/Featured-Entries#17]
When we have two Views embedded on the same page with the option "Move Featured Entries to Top" activated on both, the featured entries disappear on both Views: http://take.ms/ZxNWh

Tested with:

GV 2.1.1
Featured Entries 2.0.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/686333654/17193

**Comment by soulseekah** [comment]
While I can't reproduce the exact same symptoms in my setup (and I don't have access to debug.gv.co, please add me as a user), I managed to produce bugs wherein entries from the first view are duplicated in the second view:

![image](https://user-images.githubusercontent.com/685880/48066263-2be1ae80-e1de-11e8-8e18-35dc06861f91.png)

Not sure if related or not.

I think I found the issue and fixed it in 81a6fd0, please test :)
