### ISSUE TITLE
Featured Entries always show on top of search results

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/Featured-Entries#24]
If you add a Search Bar to a View, and perform a search, it doesn't matter if among the returned results there is a featured entry or not, they (the featured entries) will always show, regardless.

Tested on GV 2.2.4

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/991397300387786/1100689884765068)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/758363737/18666/

**Comment by soulseekah** [comment]
Please test https://github.com/gravityview/Featured-Entries/commit/a7995e90e682ddd062627b080abb91b5841c81b3 should have solved this. Thank you!

**Comment by rafaehlers** [comment]
@soulseekah that doesn't solve it.

**Comment by rafaehlers** [comment]
Related: https://github.com/gravityview/Featured-Entries/issues/15

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/857072523/20752/

**Comment by soulseekah** [comment]
Search is currently broken altogether when Featured Entries is enabled and Move To Top is enabled for the View. Working it out.

**Comment by soulseekah** [comment]
Please test and verify should work well now.

**Comment by zackkatz** [comment]
@rafaehlers @jlgrisham Please test, thanks!
