### ISSUE TITLE
Breaks searches

### ISSUE THREAD

**Issue by zackkatz** [gravityview/Featured-Entries#6]
To set up:

* Have the Page Size parameter be large enough to be bigger than the expected search results
* Filter by a dropdown field in the search bar

1. The featured entries don't have the search applied to them
1. The results overflow into additional pages with entries that don't match the search result

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/991397300387786/991506997810438)

**Comment by rafaehlers** [comment]
re: https://github.com/gravityview/GravityView/issues/1308
